### ISSUE TITLE
External themes

### ISSUE THREAD

**Issue by MarcusMann** [blogifierdotnet/Blogifier.TEMP#3]
What do you think of implementing the installation of external themes?
Can I help with this process!

**Comment by rxtur** [comment]
Hi Marcus, we currently building widgets framework which themes, naturally, will rely on. If you are interesting in the process, take a look at Blogifier.Widgets repository for couple very simple examples and then check out Newsletter project in the Blogifier.Core which is our first real full-featured widget. If you feel like building another widget of your choice and contributing it to the project - that would be terrific. I can help you along the way if needed.
Themes framework will go next and widgets will be big part of it.

**Comment by MarcusMann** [comment]
Ty @rxtur

**Comment by MarcusMann** [comment]
I want to help but I do not know where to start, I'm kind of confused because there are several applications in your repo https://github.com/blogifierdotnet

**Comment by francisdotbio** [comment]
We are changing some structure and moving repo and etc.
the main Blogifier repo is https://github.com/blogifierdotnet/blogifier/ which this weekend we are going to update master branch.

**Comment by MarcusMann** [comment]
Yeah...
I'm trying create a new theme, but ocurrs the following error:

`2017-12-03 11:36:52.969 -03:00 [Error] The view '"~/Views/Blogifier/Themes/OneThree/Single.cshtml"'`

Where is the file controller that call this file. (Single.cshtml)?

**Comment by MarcusMann** [comment]
@rxtur 

I want to help yes in the construction of widgets (plugins), I'm getting the hang of it now, but how will the install part be? How do I activate my plugin on the site?

Wait...
Because I have great ideas to implement.

**Comment by rxtur** [comment]
The quick walk-through on widgets development is in the wiki:

https://github.com/blogifierdotnet/Blogifier/wiki/Widgets

I'll be adding things there for more advanced examples. It is in the Blogifier repository, this (TEMP) repository is for archive purposes only.

There will be a site to upload widgets, Blogifier will pull them and display in the admin.
