### ISSUE TITLE
SendGrid API Key Issue

### ISSUE THREAD

**Issue by almorax** [blogifierdotnet/Blogifier.TEMP#4]
I've created an account for SendGrid API key and used the key at my blog. After this I couldn't get into the posts, that's why I removed the key from settings. But still can't get into posts.

Line 173 gives an error =>
System.ArgumentException: 'An item with the same key has already been added. Key: SendGridApiKey'

![image](https://user-images.githubusercontent.com/15785611/33514688-870f61b0-d769-11e7-8c87-7225d779989c.png)

**Comment by almorax** [comment]
There are 2 different SendGrid API key input controls.
One for general settings and the other one profile settings (edit).

What is the difference?

**Comment by rxtur** [comment]
This repository is archived, please use "Blogifier" repository for latest code.
